import { Cabin, Quicksand } from "next/font/google";
import "./globals.css";

const cabin = Cabin({
  variable: "--body-font",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--heading-font",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${cabin.variable} ${quicksand.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
